[theme]
primaryColor = "#006FCF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F4FF"
textColor = "#1A1A2E"
font = "sans serif"

[server]
runOnSave = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
